## ---------------------------
##
## Script name: NormalizeHashSeq.R
##
## Purpose of script: It normalizes the count table generated by HashSeq.
##
## Author: Farnaz Fouladi
##
## Date Created: 2021-01-28
##
## ---------------------------

rm(list=ls())

path<-"data"
#Select a study. Options: china, RYGB, vaginal, soil, autism
study="vaginal"


#*********************Functions***********************
normalize<-function(df){
  average<-mean(rowSums(df))
  df_relab<-sweep(df,1,rowSums(df),"/")
  df_norm<-log10(df_relab*average +1)
  df_norm
}

#*********************Normalize and write tables***********************
countTable<-read.table(file.path(path,study,"SVTable.txt"),sep="\t",header = TRUE,row.names = 1)
df<-normalize(countTable)
meta<-read.table(file.path(path,study,paste0(study,"_metaData.txt")),sep="\t",header = TRUE)

if(study=="soil")
  rownames(df)<-sapply(rownames(df), function(x) strsplit(x,"_")[[1]][1])

df1<-df[meta$Run,]
sum(rownames(df1)==meta$Run)==nrow(df1)

write.table(df1,file.path(path,study,paste0(study,"_SvTable_norm.txt")),sep="\t",quote = FALSE)
