## ---------------------------
##
## Script name: normalizeDADA2.R
##
## Purpose of script: Normalize the count tables generated by DADA2.
##
## Author: Farnaz Fouladi
##
## Date Created: 2021-01-28
##
## ---------------------------

rm(list=ls())

path<-"data/DADA2"
#Select a study. Options: china, RYGB, vaginal, soil, autism
study="soil"


#*********************Functions***********************
normalize<-function(df){
  average<-mean(rowSums(df))
  df_relab<-sweep(df,1,rowSums(df),"/")
  df_norm<-log10(df_relab*average +1)
  df_norm
}

#*********************Normalize and write tables***********************
countTable<-read.table(file.path(path,paste0(study,"_Dada2Reads.txt")),sep="\t",header = TRUE,row.names = 1)
df<-normalize(countTable)
meta<-read.table(file.path(path,paste0(study,"_metaData.txt")),sep="\t",header = TRUE)

df1<-df[meta$Run,]
sum(rownames(df1)==meta$Run)==nrow(df1)

write.table(df1,file.path(path,paste0(study,"_DADA2Table_norm.txt")),sep="\t",quote = FALSE)

names<-paste0("seq",1:ncol(df))
sequences<-colnames(df)
seqinr::write.fasta(as.list(sequences),names,file.path(path,paste0(study,"_sequences.fasta")),nbchar=250)


